version: '3.8'

services:
  product-service:
    build:
      context: .
      dockerfile: ProductService.Dockerfile
    container_name: product-service
    ports:
      - "5000:5000"
    depends_on:
      - mongo
      - redis
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - product-network

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      - product-network
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - product-network

networks:
  product-network:
    driver: bridge

volumes:
  mongo-data:
