version: '3.8'

services:
  product-service:
    build:
      context: .
      dockerfile: ProductService.Dockerfile
    container_name: productservice
    ports:
      - "5000:5000"
    depends_on:
      - mongo
      - redis
      - rabbitmq
    networks:
      - outdoor-network

  order-service:
    build:
      context: .
      dockerfile: OrderService.Dockerfile
    container_name: orderservice
    ports:
      - "5011:5011"
    depends_on:
      - mongo
      - redis
      - rabbitmq
    networks:
      - outdoor-network

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      - outdoor-network
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - outdoor-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - outdoor-network

networks:
  outdoor-network:

volumes:
  mongo-data:
